[package]
name = "webgraph"
version = "0.1.0"
edition = "2021"
description = "A Rust port of the WebGraph framework (http://webgraph.di.unimi.it/)."
repository = "https://github.com/vigna/webgraph-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["graph", "compression", "codes", "webgraph"]
categories = ["compression", "data-structures"]


[features]
default = ["std"]
std = ["alloc", "anyhow/std"]
alloc = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Lib dependancies
anyhow = { version = "1.0.70", default-features = false }
java-properties = "1.4.1"
mmap-rs = "0.5.0"
bitvec = { version = "1.0.1", features = ["atomic"] }
num_cpus = "1.15.0"
sux = {git = "https://github.com/vigna/sux-rs"}
dsi-bitstream = {git = "https://github.com/vigna/dsi-bitstream-rs"}
# Bin dependancies
clap = { version = "4.1.6", features = ["derive"] }
dsi-progress-logger = "0.1.0"
log = "0.4.17"
stderrlog = "0.5.4"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.7.0"
tempfile = "3.5.0"
itertools = "0.10.5"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }

[profile.release] # Used for the examples
opt-level = 3             # like --release
lto = "fat"               # Full LTO
overflow-checks = false   # Disable integer overflow checks.
debug = true              # Include debug info.
debug-assertions = false  # Enables debug assertions.
codegen-units=1           # slower compile times, but maybe better perf

[lib]
name = "webgraph"
path = "src/lib.rs"
