[package]
name = "webgraph"
version = "0.1.0"
edition = "2021"
description = "A Rust port of the WebGraph framework (http://webgraph.di.unimi.it/)."
repository = "https://github.com/vigna/webgraph-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["graph", "compression", "codes", "webgraph"]
categories = ["compression", "data-structures"]


[features]
default = ["std"]
std = ["anyhow/std"]
alloc = []
slow_tests = []
skips = []
fuzz = ["dep:arbitrary", "dep:zip", "dsi-bitstream/fuzz"]

[dependencies]
anyhow = { version = "1.0.70", features=["backtrace"]}
java-properties = "1.4.1"
mmap-rs = "0.5.0"
bitvec = { version = "1.0.1", features = ["atomic"] }
num_cpus = "1.15.0"
epserde = "0.3.1"
sux = "0.1"
dsi-bitstream = "=0.1.3"
# Bin dependancies
clap = { version = "4.1.6", features = ["derive"] }
dsi-progress-logger = "0.2.0"
log = "0.4.17"
stderrlog = "0.5.4"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.7.0"
tempfile = "3.5.0"
#itertools = "0.10.5"
bytemuck = "1.13.1"
arbitrary = { version = "1", features = ["derive"], optional = true }
zip = {version="0.6.6", optional=true}
libc = "0.2.147"
itertools = "0.11.0"
nougat = "0.2.4"
lender = "0.2.7"
common_traits = "0.10.0"
impl-tools = "0.10.0"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
env_logger = "0.9.0"

[profile.release] # Used for the examples
opt-level = 3             # like --release
lto = "fat"               # Full LTO
overflow-checks = false   # Disable integer overflow checks.
debug = true              # Include debug info.
debug-assertions = false  # Enables debug assertions.
codegen-units=1           # slower compile times, but maybe better perf

[lib]
name = "webgraph"
path = "src/lib.rs"
