[package]
name = "webgraph"
version = "0.1.0"
edition = "2021"
description = "A Rust port of the WebGraph framework (http://webgraph.di.unimi.it/)."
repository = "https://github.com/vigna/webgraph-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["graph", "compression", "codes", "webgraph"]
categories = ["compression", "data-structures"]


[features]
default = ["std"]
std = ["alloc", "anyhow/std"]
alloc = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", default-features = false }
human-repr = "1.1.0"
log = "0.4.17"
num-format = "0.4.4"
pluralizer = "0.4.0"
stderrlog = "0.5.4"
sux = {git = "https://github.com/vigna/sux-rs"}
sysinfo = "0.29.0"

[dev-dependencies]
clap = { version = "4.1.6", features = ["derive"] }
java-properties = "1.4.1"
rand = { version = "0.8.5", features = ["small_rng"] }
mmap-rs = "0.5.0"

[profile.release] # Used for the examples
opt-level = 3             # like --release
lto = "fat"               # Full LTO
overflow-checks = false   # Disable integer overflow checks.
debug = false             # Include debug info.
debug-assertions = false  # Enables debug assertions.
codegen-units=1           # slower compile times, but maybe better perf
